/**
 * 언어별 알림 메시지 템플릿 생성 (kese 블로그용으로 각색)
 */
function getNotificationMessages(language, type, data) {
  const templates = {
    ko: {
      // 일반 댓글 알림
      normal: {
        title: `[알림] ${data.title || 'Untitled'} - 새 댓글`,
        body: `${data.emoji} @${data.github} 님, 작성하신 포스트에 [${data.action}](${data.commentUrl})!

**포스트:** [${data.title || 'Untitled'}](${data.commentUrl})
**댓글 작성자:** ${data.commenter}

---

### 📋 댓글 내용
> ${data.commentBody}${data.aiSection}

---

**💬 댓글에 답변하려면 [여기](${data.commentUrl})를 클릭하세요.**

_이 알림은 GitHub Actions에 의해 자동 생성되었습니다_`
      },

      // 높은 독성 댓글 알림
      toxic: {
        title: `${data.emoji} [모더레이션 필요] ${data.title || 'Untitled'} - 부적절한 댓글`,
        body: `${data.emoji} **모더레이션이 필요한 댓글이 감지되었습니다**

**포스트:** [${data.title || 'Untitled'}](${data.commentUrl})
**댓글 작성자:** ${data.commenter}
**위험도:** Level ${data.toxicityLevel} (${data.severityLabel})
**문제점:** ${data.concerns}

${data.deletedMessage}

---

### 📋 댓글 내용
> ${data.commentBody}

---

### 🤖 AI 분석 결과

**분류:** ${data.category}
**요약:** ${data.summary}

**추천 조치:**
${data.suggestions}

---

**⚠️ 이 댓글은 자동 플래그되었으며, 관리자 검토가 필요합니다.**

**관리자:** ${data.moderators}

_이 알림은 GitHub Actions에 의해 자동 생성되었습니다_`
      },

      // GitHub ID 누락 시 Fallback 알림
      fallback: {
        title: `⚠️ [작성자 미매칭] ${data.title || 'Untitled'} - 새 댓글`,
        body: `⚠️ **GitHub ID 미등록 작성자의 포스트에 댓글이 달렸습니다**

**포스트:** [${data.title || 'Untitled'}](${data.commentUrl})
**작성자:** ${data.authorName} (ID: ${data.writerId})
**댓글 작성자:** ${data.commenter}

---

### 📋 댓글 내용
> ${data.commentBody}${data.aiSection}

---

### ⚠️ 조치 필요

**문제:** \`content/authors.yaml\`에 GitHub ID가 없어 작성자에게 직접 알림을 보낼 수 없습니다.

**해결 방법:**
1. \`kese-blog/content/authors.yaml\`에 다음 필드 추가:
   \`\`\`yaml
   - id: ${data.writerId}
     name: ${data.authorName}
     github: <username>  # 👈 추가 필요
   \`\`\`

2. 작성자에게 수동으로 댓글 알림

3. 다음 댓글부터는 자동 알림 전송됨

---

**관리자:** ${data.moderators}

_이 알림은 GitHub Actions에 의해 자동 생성되었습니다_`
      }
    },

    en: {
      normal: {
        title: `[Notification] ${data.title || 'Untitled'} - New Comment`,
        body: `${data.emoji} @${data.github}, a [comment was posted](${data.commentUrl}) on your article!

**Post:** [${data.title || 'Untitled'}](${data.commentUrl})
**Commenter:** ${data.commenter}

---

### 📋 Comment Content
> ${data.commentBody}${data.aiSection}

---

**💬 To reply to this comment, [click here](${data.commentUrl}).**

_This notification was automatically generated by GitHub Actions_`
      },

      toxic: {
        title: `${data.emoji} [Moderation Required] ${data.title || 'Untitled'} - Inappropriate Comment`,
        body: `${data.emoji} **A comment requiring moderation has been detected**

**Post:** [${data.title || 'Untitled'}](${data.commentUrl})
**Commenter:** ${data.commenter}
**Risk Level:** Level ${data.toxicityLevel} (${data.severityLabel})
**Issues:** ${data.concerns}

${data.deletedMessage}

---

### 📋 Comment Content
> ${data.commentBody}

---

### 🤖 AI Analysis

**Category:** ${data.category}
**Summary:** ${data.summary}

**Recommended Actions:**
${data.suggestions}

---

**⚠️ This comment was automatically flagged and requires moderator review.**

**Moderators:** ${data.moderators}

_This notification was automatically generated by GitHub Actions_`
      },

      fallback: {
        title: `⚠️ [Author Unmapped] ${data.title || 'Untitled'} - New Comment`,
        body: `⚠️ **A comment was posted on an article by an author without a registered GitHub ID**

**Post:** [${data.title || 'Untitled'}](${data.commentUrl})
**Author:** ${data.authorName} (ID: ${data.writerId})
**Commenter:** ${data.commenter}

---

### 📋 Comment Content
> ${data.commentBody}${data.aiSection}

---

### ⚠️ Action Required

**Issue:** The author has no GitHub ID in \`content/authors.yaml\`, so direct notification is not possible.

**Resolution:**
1. Add the github field to \`kese-blog/content/authors.yaml\`:
   \`\`\`yaml
   - id: ${data.writerId}
     name: ${data.authorName}
     github: <username>  # 👈 add this
   \`\`\`

2. Notify the author manually

3. Future comments will be notified automatically

---

**Moderators:** ${data.moderators}

_This notification was automatically generated by GitHub Actions_`
      }
    }
  };

  const langTemplates = templates[language] || templates.ko;
  const template = langTemplates[type];

  if (!template) {
    console.error(`❌ Unknown notification type: ${type}`);
    return { title: 'Notification Error', body: 'Template not found' };
  }

  return template;
}

module.exports = { getNotificationMessages };
